### PR TITLE
[main][fix] Use LP value - debt repaid in withdraw value calculation

### PR DESCRIPTION
**Pull request by alpanaca**
## Description
New calculation on withdraw value. Instead of using tokens return and assess the value. Use LP's value used in withdrawal - debt repaid.

## Why?
Old calculation lead to larger equity loss due to Worker's LP amount as an multiplier to position value changes

### Link to story (if available)

ALPACA-3574

### CODE REVIEW

**Comment by alpanaca** [comment]
Still won't solve the problem at withdrawHealthcheck() since in that function we also use equityBefore - equityAfter

**Comment by alpanaca** [comment]
@jr-alpaca Need to change how actual withdraw value in each side is calculated.

**Comment by alpanaca** [comment]
TODO: Refactor to put LP amount into positionInfo struct

**Comment by alpanaca** [comment]
> 

Done

**Review by almost-llamas — APPROVED** [review]

**Pull request merged**
